# Generated by Django 4.2 on 2023-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_score',
            field=models.IntegerField(null=True),
        ),
    ]
