# Generated by Django 4.2 on 2023-05-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_language_alter_articleversion_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
